export const NL = '\n';
export const TAB = '\t';
export const NULL = '\0';
export const SPACE = ' ';
export const OPEN_PAREN = '(';
export const CLOSE_PAREN = ')'
export const OPEN_BRACE = '[';
export const CLOSE_BRACE = ']';
export const OPEN_CURLY = '{';
export const CLOSE_CURLY = '}';
export const OPEN_ANGLE = '<';
export const CLOSE_ANGLE = '>';
export const SNG_QUT = "'";
export const DBL_QUT = '"';
export const DOLLAR = '$';
export const PERCENT = '%';
export const EXCLAM = '!';
export const QUESTION = '?'